# Generated by Django 3.2.7 on 2023-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_pain_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='image',
            field=models.FileField(upload_to='yoga/images/'),
        ),
    ]
