# Generated by Django 3.2.7 on 2023-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_yoga_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='image',
            field=models.ImageField(upload_to='yoga/images/'),
        ),
    ]
