# Generated by Django 3.2.7 on 2023-04-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pain',
            name='disease',
        ),
    ]
