# Generated by Django 4.0.6 on 2023-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_yoga_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pain',
            name='level',
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='Disease',
            field=models.ManyToManyField(blank=True, to='Main.disease'),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='Pain',
            field=models.ManyToManyField(blank=True, to='Main.pain'),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='image',
            field=models.ImageField(blank=True, upload_to='yoga/images/'),
        ),
        migrations.AlterField(
            model_name='yoga',
            name='video',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
