# Generated by Django 4.0.6 on 2023-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_pain_level_alter_disease_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoga',
            name='How_to',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yoga',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yoga',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
